### ISSUE TITLE
npm package is not the production build

### ISSUE THREAD

**Issue by adampenn** [gparlakov/forms-typed#31]
When doing a npm install of ngx-forms-typed I cannot use it in my angular app since it cant read the public api ts file. It seems like you published the dist folder of `forms` after you did a non production build. This seems to cause issues when importing your project. I did a test locally where I did a `ng build forms --prod` and published dist/forms to a local npm server i have. This resolved the issue. Can i request that you push a new prod build to npm? Please feel free to contact me with any questions

**Comment by gparlakov** [comment]
Hi @adampenn, thanks for reaching out. I'll investigate and get back to you as soon as possible. Can you confirm you are using the @latest version ~1.0.4~ 1.0.5?

**Comment by adampenn** [comment]
Yes that is the version I am using

**Comment by gparlakov** [comment]
I was able to reproduce locally and @adampenn you are absolutely correct, thanks! 

Released the 1.0.6 version and tested that it actually works :)

**Comment by adampenn** [comment]
Thank you very much for your timely response.
