### ISSUE TITLE
Incorrect README install instructions

### ISSUE THREAD

**Issue by Josh015** [gparlakov/forms-typed#52]
In your README "Getting Started" section it says to use the command `npm install --save-dev ngx-forms-typed`, but the npm page sidebar says `npm i ngx-forms-typed`. I assume it's the latter, but you might want to get those in sync.

**Comment by gparlakov** [comment]
@Josh015 thanks for your feedback. 

Why do you think these should be in sync?

**Comment by Josh015** [comment]
Well last I'd checked your package isn't a dev dependency, so its instructions should tell the user to install it like a regular dependency.

**Comment by gparlakov** [comment]
Agreed.
