### ISSUE TITLE
if form group has multiple array? how to add TypedArraysIn?

### ISSUE THREAD

**Issue by santhosh-pro** [gparlakov/forms-typed#62]
form = typedFormGroup<AddPriceRequest,TypedArraysIn<AddPriceRequest, 'prices'>>({
    isProduct: typedFormControl<boolean>(false, [Validators.required]),
    movieId:  typedFormControl<string>("", [Validators.required]),
    defaultPrice:  typedFormControl<number>(null, [Validators.required]),
    durationInDays:  typedFormControl<number>(null, [Validators.required]),
    defaultCountryId:  typedFormControl<string>(null, [Validators.required]),
    prices: typedFormArray<GetPrice>([typedFormControl()]),
   prices2: typedFormArray<GetPrice>([typedFormControl()]),
  });

**Comment by gparlakov** [comment]
Use "prices" | "prices2" to indicate the properties that are arrays. In
your example only the prices are indicated as array

**Comment by gutnar** [comment]
What if the form group has both nested `FormArray` and nested `FormGroup` properties?

**Comment by gparlakov** [comment]
Yeah that's supported too. It's the second and third type parameter. (I'm
away from keyboard and can't add an example immediately. )

**Comment by gparlakov** [comment]
@gutnar closing this issue. Ping if there's more to discuss
