### ISSUE TITLE
Adjustments to nested typedFormArray of typedFormGroups usage

### ISSUE THREAD

**Issue by maksimillian1** [gparlakov/forms-typed#63]
Hi,

using:
"@angular/core": "~12.2.0"
"forms-typed": "0.0.0-development"

Found example where you instantiate form as an example for nested typedFormArray of typedFormGroups usage:
```
export interface PersonContact {
  name: string;
  email: string;
}

export interface PartyForm {
  invitees: PersonContact[];
  event: EventForm;
}

...
export class PartyFormComponent implements OnInit {
  form = typedFormGroup<PartyForm, TypedArraysIn<PartyForm, 'invitees'>>({
    event: typedFormControl({ disabled: true, value: eventDefault() }),
    invitees: typedFormArray([typedFormControl()]),
  });
...
```
The TypedFormControl with typedFormControl function is passed into "invitees" TypedFormArray, which is semantically incorrect as it should be a TypedFormGroup instance. Also in PersonContactComponent you extended ControlValueAccessorConnector which implements ControlValueAccessor to map typedFormControl into TypedFormGroup instance. That looks like a duct tape fix which could produce bugs as you need to override default Angular's form logic and its uses subscriptions. so i suggest another approach to have fewer overheads using FormsTyped lib and cover the specified case:

Firstly in PartyFormComponent pass typedFormGroup<PersonContact> in typedFormArray
```
  form = typedFormGroup<PartyForm, TypedArraysIn<PartyForm, 'invitees'>>({
    event: typedFormControl({ disabled: true, value: eventDefault() }),
    invitees: typedFormArray([typedFormGroup<PersonContact>({
        email: typedFormControl(''),
        name: typedFormControl(''),
    }
    )]),
  });
```

Then rewrite PersonContactComponent to simple accept TypedFormControl<PersonContact> and transform it in ngOnInit into TypedFormGroup<PersonContact>

```
  @Input() personContactGroup:  TypedFormControl<PersonContact>;
  public form!: TypedFormGroup<PersonContact>;

  ngOnInit(): void {
    this.form = this.personContactGroup as TypedFormGroup<PersonContact>
  }

```
All works as expected and required less effort to set up with this approach.
@gparlakov What do you think?

**Comment by gparlakov** [comment]
Hi, @maksimillian1 

This part of your message puzzles me a bit 
> The TypedFormControl with typedFormControl function is passed into "invitees" TypedFormArray, which is semantically incorrect as it should be a TypedFormGroup instance

What would be semantically correct given the usage:
https://github.com/gparlakov/forms-typed/blob/38af73df14d3a303ae82418c5c4d540f8e720cf7/src/app/party-form/party-form.component.html#L11-L14

**Comment by maksimillian1** [comment]
Hi, @gparlakov 

I think to be more semantically correct we should consider and use "person"(formArray iterator element) as a FormGroup instance.

### Before
```
 <fty-person-contact 
   *ngFor="let person of invitees?.controls; let i = index" 
   [formControl]="person" 
 ></fty-person-contact>
```
### After
```
 <fty-person-contact 
   *ngFor="let person of invitees?.controls; let i = index" 
   [personContactGroup]="person" 
 ></fty-person-contact>
```

I suggest doing a type assertion inside the 'fty-person-contact' component to cast our person into the TypeFormGroup instance like on the example:
```
  @Input() personContactGroup:  TypedFormControl<PersonContact>;
  public form!: TypedFormGroup<PersonContact>;

  ngOnInit(): void {
    this.form = this.personContactGroup as TypedFormGroup<PersonContact>
  }

```

Then we can remove all controlValueAccessor logic in the child component.

**Comment by gparlakov** [comment]
So the goal is to avoid using ControlValueAccessor?

**Comment by maksimillian1** [comment]
@gparlakov yeah, also we get rid of additional subscriptions and mappings inside it. We rely on only the angular forms API in the result.

**Comment by gparlakov** [comment]
I guess if you really want to replace ControlValueAccessor - that would be the way to go. 

I personally wouldn't.

**Comment by gparlakov** [comment]
That said I would be curious to find out how that approach holds up in an actual app. So please share if you do use it.

**Comment by maksimillian1** [comment]
@gparlakov 
So in my example, it would look like

... <PartyFormComponent>
export class PartyFormComponent implements OnInit {
  form = typedFormGroup<PartyForm, TypedArraysIn<PartyForm, 'invitees'>>({
    event: typedFormControl({ disabled: true, value: eventDefault() }),
    invitees: typedFormArray([typedFormGroup<PersonContact>({
        email: typedFormControl(''),
        name: typedFormControl(''),
    }
    )]),
  });
  ...

...<PersonContactComponent>
export class PersonContactComponent implements OnInit {
  @Input() personContactGroup:  TypedFormControl<PersonContact>;
  public form!: TypedFormGroup<PersonContact>;

  ngOnInit(): void {
    this.form = this.personContactGroup as TypedFormGroup<PersonContact>
  }
}
...
